Vagrant.configure('2') do |config|
  config.vm.synced_folder "data", "/home/vagrant/data"
  config.vm.network "forwarded_port", guest: 80, host: 8899
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 9092, host: 9092
  config.vm.provision :shell, path: "install_docker.sh"
  config.vm.provision "shell", inline: <<-SHELL
    cd /vagrant/
    sudo docker compose up -d
  SHELL
  config.vm.provision :shell, path: "tunneling.sh"
  (1..1).each do |i|
  config.vm.define "sonarqube" do |machine|
    machine.vm.box = 'ubuntu/focal64'
    machine.vm.hostname = "sonarqube"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "sonarqube-#{i}"
      vb.cpus = '2'
      vb.memory = '4096'
    end
  end
  end
end
