#!/bin/bash

#!/bin/bash

# Update the system
sudo dnf -y update

# Add the MySQL repository
sudo dnf install -y https://dev.mysql.com/get/mysql80-community-release-el8-1.noarch.rpm

# Install MySQL server
sudo dnf install -y mysql-server

# Enable MySQL to start on boot
sudo systemctl enable mysqld

# Start the MySQL service
sudo systemctl start mysqld

# Display the status of MySQL service
sudo systemctl status mysqld

sudo systemctl enable mysqld.service

# Get the temporary root password generated by MySQL
sudo grep 'temporary password' /var/log/mysqld.log

# sudo firewall-cmd --permanent --add-service=mysql
# sudo firewall-cmd --reload