Vagrant.configure('2') do |config|
  config.vm.synced_folder "data", "/home/vagrant/data"
  config.vm.network "forwarded_port", guest: 80, host: 8899
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "forwarded_port", guest: 9100, host: 9100
  # config.vm.provision "shell", inline: <<-SHELL
  #  sudo apt update
  #  sudo apt install mysql-server -y
  # SHELL
  
  config.vm.provision :shell, path: "myscript.sh"

  (1..1).each do |i|
  config.vm.define "webserver" do |machine|
    machine.vm.box = 'ubuntu/focal64'
    machine.vm.hostname = "webserver"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "webserver_nginx-#{i}"
      vb.cpus = '2'
      vb.memory = '2048'
    end
  end
  end
end